In [1]:
import numpy as np
import pandas as pd

## Creating Dataframe

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [14]:
df2["Derignation"] = ["Doc","eng","DS","Doc"]

In [15]:
df2

    Name  Age      City  Salary Derignation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000          DS
3  Linda   42    London   85000         Doc

In [19]:
df2.drop('Derignation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2

    Name  Age      City  Salary Derignation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000          DS
3  Linda   42    London   85000         Doc

In [21]:
df2.drop(0)

    Name  Age    City  Salary Derignation
1   Anna   34   Paris   70000         eng
2  Peter   29  Berlin   62000          DS
3  Linda   42  London   85000         Doc

In [24]:
df2.loc[[0,1]]

   Name  Age      City  Salary Derignation
0  John   28  New York   65000         Doc
1  Anna   34     Paris   70000         eng

In [26]:
df2.iloc[1]

Name            Anna
Age               34
City           Paris
Salary         70000
Derignation      eng
Name: 1, dtype: object

In [28]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

Conditional

In [30]:
#I only want to see those whoes age is above 30

df2[df2["Age"] > 30]

    Name  Age    City  Salary Derignation
1   Anna   34   Paris   70000         eng
3  Linda   42  London   85000         Doc

In [32]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary Derignation
1  Anna   34  Paris   70000         eng