In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [7]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [8]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [9]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.fillna("a")

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0    a
2    a  3  3.0    a
3  4.0  4    a    a
4  5.0  5    a  5.0

In [16]:
values = {"A" : 0, "B" : 1, "C" : 2, "D" : 3}
df.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  0.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [17]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0